Created Message, Request and Response classes
gleal42/webserv pull request #37
Opened 2022-06-14 00:43 UTC by gleal42

In order to parse and validate client and server configuration messages.
Also added comments with standard fields.

2022-06-14 20:15 UTC, coderMeira reviewed
Tudo okapa. Acrescentei algums pontos de discussao quanto ao design das classes
Let's go 👾

2022-06-14 20:15 UTC, coderMeira commented on inc/Request.hpp
> +#endif
Podemos pensar na ordem de operaçoes para o parsing destes fields. 
Por ex seria melhor o Request/Response herdar uma Message, ou simplesmente passar um objecto (ou string) Message ja completo no constructor, e o parsing era feito la dentro? Depois esses dados (method, request target, http_version etc) eram atribuidos à medida que passassem nos testes do parser.

2022-06-14 23:42 UTC, gleal42 commented on inc/Message.hpp
> +		std::vector<std::string> _fields; // Different for Request and Response / CRLF (Carriage Return) inbetween them
Agreed, because we will only have unique keys

2022-06-14 23:43 UTC, gleal42 commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
Hmm, maybe.
Estava a pensar a Message ser mais para imprimir e o Request e Response mais para as validações.
Mas ambos fazem sentido.

2022-06-14 23:45 UTC, gleal42 commented on inc/Request.hpp
> +#endif
Pois, Message era mais para servir como interface para as outras 2 classes.

O Parsing podia ser lá dentro, sim! Acho que fazia sentido!

2022-06-15 16:08 UTC, mlrcbsousa requested changes

2022-06-15 16:08 UTC, mlrcbsousa commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
esses 3 elementos do start line sao cada um um member variable do request / response dependendo do caso

vai ser sempre preciso de alguma coisa como isto mas no caso do response e um metodo e no caso do request e um member variable

isto porque no caso do request e so ler do socket e set, n somos nos que construimos, mas no caso do response somos nos que construimos baseado no servicing desse request entao na altura de send_response fazemos primeiro um send header que chama um status_line (start_line da response) mas que constroi isso a partir dos 2 member values que precisa (resultantes do servicing) portanto n precisamos de set o start line no response pq se nao vamos tar a fazer extra de cada vez

imagina, mudamos o http code ao service o request, entao precismo tb de set o startline, vamos tar a set de cada vez mais variaveis do que necessarias pq a start line vai sempre depender de 2 ou mais outras variaveis

logo melhor construir o start_lie baseado no current state dessas variaveis que o compoem na altura em que for para send_response_header

2022-06-15 16:08 UTC, mlrcbsousa commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
e entao ter um member var no request e um member function no response, o q anula a sua presenca como parte do interface

2022-06-15 16:32 UTC, gleal42 commented on inc/Server.hpp
> +
Pois, faz sentido. Temos de ver como isto fica com os polls.

2022-06-15 16:40 UTC, gleal42 commented on inc/Server.hpp
> +// Server will have multiple requests and responses so maybe a vector is more adequate
Yes we need to add some parser for the message received by the client so we can send the appropriate response. Not sure if this is what you're referring to.

2022-06-15 16:44 UTC, gleal42 commented on inc/ServerConfig.hpp
> +		int	getReturn();
Return Directive:
https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return

Maybe we don't need to implement.

2022-06-15 16:47 UTC, gleal42 commented on srcs/Message.cpp
> +const std::string Message::getMessage() const
Yeah, can't think of any functions in common.

But I believe it would make it more readable for someone following the RFC:
https://www.rfc-editor.org/rfc/rfc9112.html

2022-06-15 16:47 UTC, gleal42 commented on srcs/Response.cpp
> +Response::Response(void)
Yes.

2022-06-16 01:57 UTC, gleal42 commented on inc/Message.hpp
> +		std::vector<std::string> _fields; // Different for Request and Response / CRLF (Carriage Return) inbetween them
But we have to make sure that the order is not important. Otherwise it will have to go back to vector/deque

2022-06-16 13:55 UTC, mlrcbsousa commented on srcs/Message.cpp
> +const std::string Message::getMessage() const
agreed

2022-06-16 13:55 UTC, mlrcbsousa commented on inc/ServerConfig.hpp
> +		int	getReturn();
hmm idk

2022-06-16 14:23 UTC, gleal42 commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
I think I get it.

But even though you called this class Message some of these variables belong only to the request (method and uri).

But I'll add the list of methods to an Enum.

2022-06-16 14:41 UTC, gleal42 commented on inc/Server.hpp
> +// Server will have multiple requests and responses so maybe a vector is more adequate
Got it. Will implement them here.

2022-06-17 07:49 UTC, mlrcbsousa commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
> remove start line from Message (done)

Also remembered something about this one. The first line has different content based on if it is a request or response. The request has http version, method and uri. And the response has http version http code and phrase. So indeed they are quite different to be a common trait, not only in the technical perspective of one being a member variable and the other a function.

> Remove body from Message (not sure about this one). Might be useful for post requests.

Yes both have a body. The thing is in the request that body is a member variable called like this on the request object 'req.body', and in the response it is a dynamic method with logic inside it called like this on the response object 'res.body()' so they can't be a shareable trait inherited from a parent class because of the technical incompatibility where one is a variable and the other a method.

> Remove all variables from Request because we only need to parse it to creaye our Response?

Depends on the case I think, some make sense to keep as variables, because they are core etc. but indeed some not. We can agree on these in theory on the sudocode PR and then be able to make these implementations confidently.

> In your example the class message has method and uri which belong exclusively to request.

Yes indeed I think that is one of those cases similar to the question above and I've also asked myself why they put it on the response object in the codebases I've looked at. Indeed I dnt think they are directly needed either and probably the reason for them being there is logging or some form of tracking. 

But maybe the response.send_response() method will need them, so we can comment it out of the sudocode PR while we are not sure.

2022-06-17 17:47 UTC, gleal42 commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
Okay, so now Message interface is useless because we removed everything from it so I will delete it.

2022-06-17 18:08 UTC, mlrcbsousa commented on inc/Message.hpp
> +		std::string _start_line; // Different for Request and Response
@gleal42 

No its totally not useless and a very good idea. 

If you want to keep the sudocode.hpp like it is these are the common things between the two that we can put in a interface

```cpp
enum RequestMethod {
    GET,
    POST,
    DELETE,
};

typedef std::map<std::string, std::string> MessageHeader;

class Message {
    RequestMethod    request_method;
    MessageHeader    header;
    URI              request_uri;              // The parsed URI of the request
    void             each(Function pointer);   // Iterates over each header in the request
    // Retrieves the header +field+
    std::string operator [](std::string field) const {return header[field];}
    int              content_length( void );   // The content-length header
    std::string      content_type( void );     // The content-type header
    Message(ServerConfig config);
};
```

if you want to change the hpp and remove some stuff let me know aswell, but even if we remove stuff seems like its still useful to have the interface

2022-06-19 08:05 UTC, merged