Gl/feature/initial kqueue
gleal42/webserv pull request #49
Opened 2022-07-04 21:36 UTC by gleal42

#9 Tackling this issue:

## Summary:
- Added bash script to close open socket fds in port 8080
- I was getting circular dependency so I moved around some functions in header files (feel free to find another disposition that makes sense).
- Created Kqueue logic:
  - Add server fd to kqueue
  - When client enters for the first time in the port there is an event to create that client
  - Add client fd to kqueue
  - Once fd is in kqueue we track reading and writing
- Added some interaction between Request and Response (so I could test the image). Image is still not being completely displayed.
- Added 1 unit test (maybe it makes more sense e2e for kqueue).

2022-07-04 21:50 UTC, gleal42 commented on .gitignore
> +.DS_Store
Kept adding this file by mistake so I added it to gitignore. Is that alright?

2022-07-04 21:51 UTC, gleal42 commented on close_fds.sh
> +#!/bin/bash
Script to close open fds in 8080.
Maybe I could ask the user (us) for the ports that we think are open.

2022-07-04 21:51 UTC, gleal42 commented on inc/HTTPStatus.hpp
> +HTTPStatusGroup	http_group( int code )
Was getting compilation error

2022-07-04 21:53 UTC, gleal42 commented on inc/Request.hpp
> +	Request( ServerConfig const & config );
Started changing the way functions are declared to match with the rest of the files.
I may have forgotten to do this in other files.

2022-07-04 21:55 UTC, gleal42 commented on inc/Response.hpp
> +	int 		_status;
Perhaps we don't need to save these variables. 
However some info should be stored with constructor, right?

2022-07-04 21:56 UTC, gleal42 commented on inc/Server.hpp
> +// Apagar depois
Whoops! I can delete thisl

2022-07-04 21:57 UTC, gleal42 commented on inc/Server.hpp
> +	Server( void );
To ensure that Servers always have a matching config file.

2022-07-04 21:58 UTC, gleal42 commented on inc/utils.hpp
> +#endif
I was getting circular dependency so I separated this into its own file and header file to see if it helped.

2022-07-04 21:59 UTC, gleal42 commented on src/ConfigParser.cpp
> +	_configs[0].name = "Hello";
So that config starts interacting with Response.

2022-07-04 22:01 UTC, gleal42 commented on src/Response.cpp
> +: _status(200)
The status initialization list needs to be deleted in the future.
Only temporary once HTTPStatus are not implemented.

2022-07-04 22:02 UTC, gleal42 commented on src/Response.cpp
> +	if (request._unparsed_uri == "/favicon.ico")
Browsers always do 2 requests. One for website itself and another for favicon.
I don't know if we need to deal with favicon. I'll research what to do.
Maybe we could add a default one later.

2022-07-04 22:04 UTC, gleal42 commented on src/Response.cpp
> +}
These Attribute handling perhaps needs to be done in a separate function/ map of functions/ template.

2022-07-07 17:10 UTC, coderMeira commented on src/Kqueue.cpp
> +}
Máquina! Amazing job. Can't wait to test it out on Linx

2022-07-07 17:11 UTC, coderMeira commented on src/Request.cpp
> +	_attributes = param._attributes;
Weren't we going to delete these vars?

2022-07-07 17:47 UTC, gleal42 commented on src/Kqueue.cpp
> +}
Pois. Para Linux deve ter de ser com epoll. Mas crio uma branch para essa implementação. Maybe? O Manel disse que tb tinha curiosidade em experimentar.

2022-07-07 17:53 UTC, coderMeira commented on src/Request.cpp
> +	_attributes = param._attributes;
Yeah a call would be nice, with all these changes. To follow up in a more centralized way

2022-07-08 09:07 UTC, mlrcbsousa commented on inc/Response.hpp
> +	int 		_status;
we do need this as a variable to be read later when building the response to send in send_response, they are sometimes methods in the equivalently named ones on the request because they are sometimes parsed or part of som logic that needs to be dynamic

2022-07-08 09:08 UTC, mlrcbsousa commented on src/ConfigParser.cpp
> +	_configs[0].name = "Hello";
dont understand

2022-07-08 09:10 UTC, mlrcbsousa commented on src/Response.cpp
> +}
yes I was planning to work on that next by making a message interface tat allows to set headers via the [] operator

2022-07-08 09:18 UTC, mlrcbsousa commented on src/Kqueue.cpp
> +}
ya temos de fazer em passos porque vai ser preciso abstrair algumas partes q sao especificas a cada um ptt vao precisar de uma abstracao que as englobe as duas

2022-07-08 11:00 UTC, mlrcbsousa requested changes
Very cool that you went and learned the mechanisms around the Kqueue function and implemented them ono this PR.

I really don't agree with the design choice of having the queue abstraction above the server one. To me each server manages their own queue of connections. Starts and stops accordingly and manages the way they service said requests coming from these connections based on their own server config.

What you have done with this design choice of one central queue management is hoisted all the logic of the Socket up to the Server via the new wrapper methods on server that just call underlying methods on the server socket, and then passed down to the socket class a lot of abstractions it has no business being aware of so that you can keep the link of the socket to the server which would be implicit in a scenario or server independent managed queues.

In fact the number 10 you use in the list of queues is itself a server config variable so I really don't see how this design choice is even feasible. There is nothing that blocks us from having individual server managed queues and you already did very well in isolating that logic in its own class. 

this design choice makes things more confusing to understand and messy in terms of isolated logical concerns that don't need to be aware of more than they are going to use in their lifecycle. 

All the set_parent logic and other extra logic added to maintain this link of sockets to each server from outside the server, and passing objects of totally unrelated concerns to basic objects like the socket, or turning the server into basically another socket class or expanding the concerns of the response class and again passing it to simple objects unnecessarily  can be avoided.

How do you catch and handle separately errors happening in this one overarching queue and handle them accordingly to the request / response without a tone of extra server logic on the queue or cluster.

Same question for all the other configurations. All this server specific logic now needs an extra conditional for each server because what should be done inside it is done outside it at a higher level abstraction. How is that helping the isolation and clear definition of the server's logical concerns.

if you have a method that looks like this:
```cpp
void do_something( Foo bar ) {
  bar.a = bar.b + bar.c
  bar.do_thing
  int d = bar.get_d
  bar.process_d(d)
}
```
It is a clear indication that this method should be inside the Foo class, given that everything is being called on it.

How do you cleanly shutoff one server (port)?

The separate logical concerns are something like this:

1. one or many server configurations are parsed from a file or by default
2. one (Server) or multiple (Cluster) are created for each of these configurations
3. each Server starts by setting up their main socket and listening on a different port
4. each Server handles their own multiple connection queue based on their specific configurations
5. every time a specific server receives new events on their connection queues they handle them appropriately, either by creating new ones to add to their queue or reading from already open ones
6. once everything has been read from an individual client socket is then ready to be serviced and handled in the HTTP request / response cycle
7. a Request and Response are now created with the server config in order to start doing this
8. both are 'serviced' meaning, depending on the server configuration the Request object is filled out base don the full data read form the socket and the Response is set and made to be ready to be sent on the socket
9. errors are handled at this step using http statuses in order to fill in the response accordingly with the http compliant information (status and headers)
10. response is sent, read socket is closed
11. process repeats, server waits until another of its connection has received everything on one of its open connections to start servicing and responding and closing

Sorry for the wall of text. I hope it's clear. This is not the way to go, it is causing and will cause a lot of confusing code and headaches down the line. It is hard to conceive of logically and doesn't make a lot of sense once you think of the logical concerns in the list above.

I think it's a good idea to encapsulate the queue management in its own class, it should have a more generalised name so we can have its inside logic depend on the operating system cleanly. However it does not make sense as a parent concern to the server, it should be an element of each server and handle the connections specific to that server alone.

2022-07-08 11:12 UTC, gleal42 commented on inc/Kqueue.hpp
> +   	struct kevent 		ListQueue[10];
Each connection might receive multiple requests at the same time and each server can receive a connection request.

E.g. on our html page we always receive 2 requests. One for html and the other for favico.ico

If we have 3 servers with 10 connections this could mean like 20 events at the same time.

I put 10 for now but I can put more once we start testing with more connections/ servers.

2022-07-08 11:14 UTC, gleal42 commented on inc/Response.hpp
> +	ResponseAttributes	_attributes;			// Map of request attributes
Have to double check. For Request we have this but for Response I wasnt finding it in master.

2022-07-08 11:15 UTC, gleal42 commented on inc/Server.hpp
> +# include <errno.h>
Yes I used it for debug. I'll delete it.

2022-07-08 11:28 UTC, gleal42 commented on inc/Socket.hpp
> +	void			set_parent( Server *server );
Yes but couldnt we consider connection socket a child of server socket since we need to pass server fd to create a connection?

2022-07-08 11:30 UTC, gleal42 commented on src/Kqueue.cpp
> +    Javascript (later)
Yes. These were notes from our call.

2022-07-08 11:33 UTC, gleal42 commented on src/Kqueue.cpp
> +	kevent(this->_fd, &kev, 1, NULL, 0, NULL);
Changing kevent struct to set different bits/options.
Then adding that event to kqueue

2022-07-08 11:36 UTC, gleal42 commented on src/Kqueue.cpp
> +        if (nbr_events <= 0)
If there's an error it could be -1.
I'll add an exception in this case.

2022-07-08 11:39 UTC, gleal42 commented on src/Kqueue.cpp
> +        for (int i = 0; i < nbr_events; i++)
Read and write operations.
Either new connections, new requests or new responses.

2022-07-08 11:40 UTC, gleal42 commented on inc/Kqueue.hpp
> +   	struct kevent 		ListQueue[10];
An array of events.

2022-07-08 11:45 UTC, gleal42 commented on src/Socket.cpp
> +	request = server->socket()->request;
This only applies to connections.
Just a way to identify if we're dealing with a server or connection socket.

2022-07-08 12:46 UTC, gleal42 commented on inc/Response.hpp
> +	int 		_status;
Then I didn't need to delete message class.

2022-07-08 12:47 UTC, gleal42 commented on src/ConfigParser.cpp
> +	_configs[0].name = "Hello";
So that server name is that of the config.

2022-07-12 21:47 UTC, gleal42 commented
Decided to merge a different way.

2022-07-12 21:47 UTC, closed without merging