Gl/feature/cgi
gleal42/webserv pull request #59
Opened 2022-08-06 18:08 UTC by gleal42

In this pull request I've added:
- CGI Handler
- PHP Scripts to work with CGI
- I tried creating a cpp executable to use with cgi-tester but it didn't work (maybe it will be useful once we execute the general tester).
- General and file related util functions (some of them came from Filehandler). Not sure if you like the approach or if you prefer to keep them in Filehandler.

2022-08-18 17:29 UTC, mlrcbsousa requested changes
This is just my first review.

2022-08-18 17:29 UTC, mlrcbsousa commented on src/CGIHandler.cpp
> +/*
thanks for these explanations

2022-08-18 17:29 UTC, mlrcbsousa commented on src/CGIHandler.cpp
> +	Does it make sense to turn Req method into string instead of enum
what about a request method to_str method that has the req_methods map?

2022-08-18 17:29 UTC, mlrcbsousa commented on src/CGIHandler.cpp
> +	setenv(buf, "REQUEST_METHOD", req_method[req.request_method]);
is it in the RFC this env variables list?

very cool btw

2022-08-18 17:29 UTC, mlrcbsousa commented on src/CGIHandler.cpp
> +std::vector<std::vector <char> >	CGIHandler::environment_variables( Request & req )
Small side note but this way of writing it to me is hard to read: `std::vector<std::vector <char> >`

I understand you need the space on the `> >` part because it will be interpreted as the bit shifting or `>>` operator but the first space I think could be better placed what do you think of this

```cpp
std::vector< std::vector<char> >
```

2022-08-18 21:11 UTC, gleal42 commented on Makefile
> +		utils_url.cpp \
Agreed!

2022-08-18 21:18 UTC, gleal42 commented on src/CGIHandler.cpp
> +: path(remove_query_string(uri)), query_string(get_query_string(uri)), extension(get_extension(path)), interpreter(extension_interpreter[extension])
Yes. In the new branch I started using that URI object that we had in Requests. I will try to use it here as well.

2022-08-18 21:23 UTC, gleal42 commented on src/CGIHandler.cpp
> +	- Standard Input with request body (in case of Post requests)
Not necessarily.

In the case of shared memory we could get a pointer to an array of chars that could be used in parent and child processes.

This logic of using the standard output and standard input (with the pipe logic that we used in minishell) is just one of the ways of communicating between processes.

Another way could be sockets but it could raise questions during evaluation.

2022-08-18 21:29 UTC, gleal42 commented on src/CGIHandler.cpp
> +	not much I can do about it.
Exactly. The vectors of vectors and the push_back take up a lot of lines but I they need to be in the same scope.
But maybe the first 10 lines could be in a different function.

2022-08-18 21:32 UTC, gleal42 commented on src/CGIHandler.cpp
> +		char *const *envs = env_vars.data();
Oh yeah. That was a headache. I thought it was the same but the compiler said I couldn't convert one to the other.
One is a constant pointer to a char pointer and the other is a pointer to a constant char pointer.
Not sure which, though.

2022-08-18 21:33 UTC, gleal42 commented on src/CGIHandler.cpp
> +		for (size_t i = 0; i < env_vars.size() - 1; i++) {
Sure

2022-08-18 21:36 UTC, gleal42 commented on src/CGIHandler.cpp
> +		std::vector<char> cmd_vec = convert_to_char_vector(filename(interpreter).c_str());
Here I'm using the vectors as allocators for the execve.
The second argument of execve is the program arguments.
However the first argv is always the name of the program itself (interpreter).

2022-08-18 21:38 UTC, gleal42 commented on src/CGIHandler.cpp
> +		std::vector<char> fp_vec = convert_to_char_vector(path.c_str() + 1);
filepath. Maybe I can just call it `script`?

2022-08-18 21:39 UTC, gleal42 commented on src/CGIHandler.cpp
> +/*
My pleasure

2022-08-18 21:40 UTC, gleal42 commented on src/CGIHandler.cpp
> +	Does it make sense to turn Req method into string instead of enum
Nice!

2022-08-18 21:40 UTC, gleal42 commented on src/CGIHandler.cpp
> +std::vector<std::vector <char> >	CGIHandler::environment_variables( Request & req )
Sure! I can add that extra space.

2022-08-18 22:09 UTC, gleal42 commented on src/CGIHandler.cpp
> +	setenv(buf, "REQUEST_METHOD", req_method[req.request_method]);
https://www.rfc-editor.org/rfc/rfc3875#section-4.1.1
Yes, all except SCRIPT_FILENAME which is specific to PHP CGI.
I can add an extra condition (if php then add this one).

Also missing:
AUTH_TYPE - Relacionado com o header Authorization. Ainda não demos servicing a nada relacionado com isto.

PATH_TRANSLATED -  fazer decode ao url do path enviado pelo browser.
Ainda não está mas já vi que é só passar o uri::decode().

REMOTE_ADDR - 
Só agora com esta branch é que aprendi a trabalhar com as address structures.
Temos de ir buscar isto ao accept do socket.

REMOTE_HOST
Same as before. Nova função getnameinfo() só aprendi a usar agora. 

REMOTE_IDENT 
"The server may choose not to support this feature" - CGI RFC

REMOTE_USER - Part of user authentication (não temos).

SCRIPT_NAME - Não sei porque tirei. Acho que antes tinha este e depois mudei para SCRIPT_FILENAME para funcionar no PHP.
Vou voltar a por.
SERVER_NAME - Hostname que vem nos Headers.
SERVER_PORT - Port do request
SERVER_SOFTWARE - Nome dado por nós

2022-08-18 22:11 UTC, gleal42 commented on src/CGIHandler.cpp
> +	setenv(buf, "REQUEST_METHOD", req_method[req.request_method]);
Destes que falei acho que AUTH_TYPE, REMOTE_IDENT e REMOTE_USER não vale a pena colocar. O que acham?

2022-08-18 22:18 UTC, gleal42 commented on src/CGIHandler.cpp
> +	setenv(buf, "REQUEST_METHOD", req_method[req.request_method]);
Ah, já agora. A razão porque não coloquei foi porque a PHP CGI funcionava mesmo sem eles.
Vou começar a acrescentar estes que faltam.

2022-08-19 15:57 UTC, coderMeira reviewed
Amazing job, like always. So thankful to be working with such geniuses :muscle: 
A few points:

- This will need to work with the variables parsed from the config file.
- Regarding naming conventions, in my opinion it would be nice to have utils files named like url_utils and file_utils. Also a couple functions could use a little switch (setsen->set_env && convert_to_charptr->convert_to_charptr_vec)
- Some minor optimization suggestions in the comments
- Not an issue, but personally having so many conversions to and from char vectors seem like could be troublesome in the future. but if it works it works (`CGIHandler::execute_cgi_script`)
Happy coding :space_invader:

2022-08-19 15:57 UTC, coderMeira commented on src/Server.cpp
> +        }
Hm. Let's make a function to deal with this, to avoid code duplication?

2022-08-19 15:57 UTC, coderMeira commented on src/utils_file.cpp
> +}
:clap: bravo! these are very useful

2022-08-19 15:57 UTC, coderMeira commented on test/cgi/php/get_post_file.php
> +   if (isset($name) && !empty($name)) {
both doing pretty much the same. perhaps you meant to check $separator?

2022-08-19 17:53 UTC, gleal42 commented on src/CGIHandler.cpp
> +	not much I can do about it.
For example:
I can't have a function that takes std::vector< std::vector<char> > as argument and return std::vector<char *> because the vector returned would point to garbage.
At least that's the way I remember.
But maybe I was was using a copy and not a reference. I would have to try to do it again.

2022-08-19 19:52 UTC, gleal42 commented on inc/utils_file.hpp
> +# define __UTILS_FILE_H__
I just wanted them to be all together in the VSCode explorer.

2022-08-19 19:53 UTC, gleal42 commented on src/FileHandler.cpp
> +		start_file = multi_form.find(D_CRLF) + 4;
Yeah, maybe throw a bad request. Will add it.

2022-08-19 19:56 UTC, gleal42 commented on src/FileHandler.cpp
> +		return filename;
Sure. It was better for debugging but now I can switch.

2022-08-19 20:01 UTC, gleal42 commented on src/FileHandler.cpp
>  		res._uri = "index.html";
I already semi-implemented the index directive in the branch gl/tests/42_tester.
Check it out to take some ideas if you're going that route.

2022-08-19 20:11 UTC, gleal42 commented on src/CGIHandler.cpp
> +	buf.push_back(std::vector<char>(env_var.begin(), env_var.end()));
The reason I did all these conversions was because of execve.
Because it only takes char pointer pointers char **.
In C we would use a double malloc.
Here i'm using the vector Allocator instead.
Yeah. It works for PHP CGI already.

2022-08-19 20:18 UTC, gleal42 commented on src/CGIHandler.cpp
> +		res.delete_header("Status");
Because Status is not a HTTP Response Header.

It is a CGI Header to let us know what we will have in the first line:
e.g. `HTTP/1.1 200 OK`

2022-08-19 20:28 UTC, gleal42 commented on test/cgi/php/get_post_file.php
> +   if (isset($name) && !empty($name)) {
No, one checks if the variable is set and the other checks if the value associated to the variable is empty:
https://www.geeksforgeeks.org/difference-between-isset-and-empty-functions/

Basically when we  fill out the html form, if we leave some parts empty sometimes the PHP doesn't even set the variables. Other times it sets the variables but the values associated with it are empty (empty string).

2022-08-19 20:32 UTC, gleal42 commented on src/CGIHandler.cpp
> +		std::vector<char> cmd_vec = convert_to_char_vector(filename(interpreter).c_str());
I'm not entirely sure, because this will supposedly be used by the CGI program, which might be located in a different path compared to our program.

2022-08-19 20:42 UTC, gleal42 commented on src/Response.cpp
> +			throw HTTPStatus<400>();
Hmmm.. probably. Can we? 
My parsing is very "trial and errory" so i'm not 100% sure.

2022-08-19 21:02 UTC, mlrcbsousa requested changes
Second review, still need to complete the full PR.

2022-08-19 21:11 UTC, gleal42 commented on src/Server.cpp
> +        }
Sure.

2022-08-19 21:25 UTC, gleal42 commented on Makefile
> +		utils_url.cpp \
https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/Makefile#L23-L24

2022-08-19 21:27 UTC, gleal42 commented on inc/CGIHandler.hpp
> +	void			set_response( std::string bdy, Response &res );
https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/inc/CGIHandler.hpp#L55

2022-08-19 21:28 UTC, gleal42 commented on src/CGIHandler.cpp
> +: path(remove_query_string(uri)), query_string(get_query_string(uri)), extension(get_extension(path)), interpreter(extension_interpreter[extension])
https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/CGIHandler.cpp#L46-L47

2022-08-19 21:29 UTC, gleal42 commented on src/CGIHandler.cpp
> +		std::vector<char> fp_vec = convert_to_char_vector(path.c_str() + 1);
https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/CGIHandler.cpp#L149-L151

2022-08-19 21:31 UTC, gleal42 commented on src/CGIHandler.cpp
> +		for (size_t i = 0; i < env_vars.size() - 1; i++) {
https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/CGIHandler.cpp#L144-L146

https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/inc/print.hpp#L18-L29

https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/print.cpp#L4-L10

2022-08-19 21:34 UTC, gleal42 commented on src/CGIHandler.cpp
> +	Does it make sense to turn Req method into string instead of enum
Something like this??

https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/Request.cpp#L19-L28

https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/Request.cpp#L262-L271

2022-08-19 21:35 UTC, gleal42 commented on src/CGIHandler.cpp
> +	setenv(buf, "REQUEST_METHOD", req_method[req.request_method]);
@coderMeira https://github.com/gleal42/webserv/blob/6ba932b5fff605d4a1437ce907aa40a94f33bb5c/src/CGIHandler.cpp#L220

2022-08-19 21:43 UTC, gleal42 commented on src/CGIHandler.cpp
> +std::vector<std::vector <char> >	CGIHandler::environment_variables( Request & req )
https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/CGIHandler.cpp#L203

2022-08-19 21:46 UTC, gleal42 commented on src/FileHandler.cpp
> +		start_file = multi_form.find(D_CRLF) + 4;
https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/FileHandler.cpp#L137-L141

2022-08-19 21:47 UTC, gleal42 commented on src/FileHandler.cpp
> +		return filename;
https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/FileHandler.cpp#L170-L171

2022-08-19 21:50 UTC, gleal42 commented on src/CGIHandler.cpp
> +		convert_to_charptr(buf, env_vars);
https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/CGIHandler.cpp#L206-L216

https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/CGIHandler.cpp#L141-L144

2022-08-19 21:51 UTC, gleal42 commented on src/Response.cpp
> +		str = _headers[name];
https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/Response.cpp#L153-L159

2022-08-19 21:53 UTC, gleal42 commented on src/Server.cpp
> +        }
https://github.com/gleal42/webserv/blob/b3e4c2286e491a0bd31d1b6431a16567b3a91824/src/Server.cpp#L187-L198

2022-08-20 13:14 UTC, mlrcbsousa commented on src/CGIHandler.cpp
> +	Does it make sense to turn Req method into string instead of enum
Yes top, I would put a static variable in the to_str method with the contents of the init_map function. And I think at this point the method has passed through a validation already so the throw would have already happened, so I would say not needed here.

2022-08-22 13:26 UTC, mlrcbsousa requested changes

2022-08-22 13:26 UTC, mlrcbsousa commented on src/Server.cpp
> +        return (new CGIHandler(uri));
Why do you need a memory allocation for this? If you put this method inside the service method, so no method returning object.

2022-08-22 13:26 UTC, mlrcbsousa commented on src/file.cpp
> +	void	build_error_page( const BaseStatus &error_status, Response &res )
I dont think this should be a file namespace function if it is an operation being done on the Response object. Should be in the Response class.

2022-08-22 13:26 UTC, mlrcbsousa commented on src/print.cpp
> +void	print(char *const *envs, size_t size)
Cool!

Name is a bit too general, as soon as you add another function here, like to print headers or w/e this name would need to be changed to something else. Like `print_env_variables` or something

2022-08-22 13:26 UTC, mlrcbsousa commented on src/utils.cpp
> +    {
This is curly brackets around a code snippet?

2022-08-22 13:26 UTC, mlrcbsousa commented on test/cgi/php/get_post_file.php
> +   echo "<h1> List of files </h1>";
is echo doing standard out here?

2022-08-22 19:09 UTC, gleal42 commented on src/Server.cpp
> +        return (new CGIHandler(uri));
Sorry I don' understand what you mean.

I return CGIhandler or Filehandler pointer 
 to avoid code duplication in Server::service() as requested by @fmeira. What implementation are you suggesting?

2022-08-22 19:23 UTC, gleal42 commented on test/cgi/php/get_post_file.php
> +   echo "<h1> List of files </h1>";
https://stackoverflow.com/questions/7186189/what-is-the-meaning-of-php-input-php-output-and-when-it-needs-to-use

2022-08-22 20:06 UTC, mlrcbsousa commented on src/Server.cpp
> +        return (new CGIHandler(uri));
Ah sorry not aware of Fred's suggestion, is it related to this? I'll try to find it.

Question is why do we need a new / delete here? Is it because you split the method and have to return an object from the extracted method? If so why not extract the `try` block instead or keep the 2 methods in one, and avoid the need for the new / delete? @gleal42

2022-08-22 22:42 UTC, gleal42 commented on src/Server.cpp
> +        return (new CGIHandler(uri));
Antes o código estava:
```
if (extension_is_implemented
{
CGIHandler handler (req._path );
try {
handler.service(req, res); res.build_message(handler.script_status();
} catch (BaseStatus &error_status) {
file::build_error_page(error_status, res);
}
else 
{
FileHandler handler;
try {
handler.service(req, res);
res.build_message (HTTPStatus<200>());
} catch (BaseStatus &error_status) {
file::build_error_page(error_status, res);
}
```

Agora está apenas:
```
Handler = choosehandler()
Handler.service()
Res.build_message()
catch (BaseStatus &error_status) {
file::build_error_page(error_status, res);
}
```
Ou seja, não duplicado.

Tenho de usar o new para conseguir converter o tanto o Filehandler como o CGIhandler em Handler Pointer. Para executar as funções (cada uma das funções foi substituída usando o virtual daí não haver duplication agora).

2022-08-25 22:31 UTC, gleal42 commented on src/utils.cpp
> +    {
Don't understand. These curly brackets are around code, yes.

2022-08-25 22:45 UTC, gleal42 commented on src/CGIHandler.cpp
> +BaseStatus CGIHandler::script_status( void )
My compiler tells me that status code can't be a lvalue. Meaning that it can't be a variable. 
It needs to be HTTPStatus<VALUE>(). It can't be
```
int a = 5;
HTTPStatus<a>()
```

Which makes sense because templates are created at compile time and not runtime.

2022-08-25 22:48 UTC, gleal42 commented on src/utils.cpp
> +void	print_address(const std::string &name, struct sockaddr *address)
https://github.com/gleal42/webserv/blob/c829feb2b9b3f6e5151f1f2211af08b029eab581/src/print.cpp#L12

2022-08-25 22:48 UTC, gleal42 commented on src/print.cpp
> +void	print(char *const *envs, size_t size)
https://github.com/gleal42/webserv/blob/c829feb2b9b3f6e5151f1f2211af08b029eab581/src/print.cpp#L4

2022-08-25 22:57 UTC, gleal42 commented on src/file.cpp
> +	void	build_error_page( const BaseStatus &error_status, Response &res )
Makes sense. Looks more clean!

2022-08-25 23:02 UTC, gleal42 commented on src/file.cpp
> +	void	build_error_page( const BaseStatus &error_status, Response &res )
https://github.com/gleal42/webserv/blob/3009667cb7732968260f71e27aef0daec279ff8c/src/Response.cpp#L107-L113

https://github.com/gleal42/webserv/blob/3009667cb7732968260f71e27aef0daec279ff8c/src/Server.cpp#L191-L196

2022-08-29 20:55 UTC, mlrcbsousa commented on src/CGIHandler.cpp
> +BaseStatus CGIHandler::script_status( void )
indeed makes sense

2022-08-29 20:56 UTC, mlrcbsousa commented on src/file.cpp
> +	void	build_error_page( const BaseStatus &error_status, Response &res )
prefect

2022-08-29 20:57 UTC, mlrcbsousa commented on src/utils.cpp
> +    {
sorry they were indented weirdly by GitHub so hard to see what they where wrapping

2022-09-01 13:31 UTC, merged