Gl/add cgi executable
gleal42/webserv pull request #73
Opened 2022-09-09 00:36 UTC by gleal42

### Small PR to add cgi executables.

I adjusted the CGIHandler class accordingly. 

Maybe we could even delete CGIHandler static variables and replace them with the config logic now.

What do you think?

Because CGI doesn't really exist in NGINX I'm not sure if the executable validation should be done at config level or later.

2022-09-09 08:27 UTC, mlrcbsousa commented
> I adjusted the CGIHandler class accordingly.

Noice thanks

> Maybe we could even delete CGIHandler static variables and replace them with the config logic now.

what would this mean more specifically?

> Because CGI doesn't really exist in NGINX I'm not sure if the executable validation should be done at config level or later.

Also not sure I'm following, seems to me should be done at config level, what sort of validation are you talking about?

2022-09-09 08:37 UTC, mlrcbsousa requested changes
LGTM

Couple of things though. Please keep only actual test related files in the test folder. Unit tests, end-to-end tests, nginx compare tests, etc. Implementation files like the binaries should be in their own codebase domain, for the case of the binaries I would go with a `bin/` fodler

2022-09-09 08:37 UTC, mlrcbsousa commented on src/utils.cpp
> +void			URI::clear( void )
should be method in URI class in its own file

2022-09-09 08:37 UTC, mlrcbsousa commented on scripts/manual.sh
> +docker run --rm --security-opt seccomp=unconfined -it --name fred_server -v $(PWD):/usr/src/webserv -p 8080:8080 fred_server
`fred_server` is a name that doesnt get across the purpose of the thing

2022-09-09 08:37 UTC, mlrcbsousa commented on Dockerfile
> +EXPOSE 8080
why is this needed? in order to have this variable dynamic with the e2e tests / matching the config, we would need to get it from the config files somehow

2022-09-10 18:23 UTC, gleal42 commented on Dockerfile
> +EXPOSE 8080
Pois, não me estava a reconhecer of requests então achei que fosse isto. Posso double check a ver se existe outra maneira.

2022-09-10 18:40 UTC, merged